'use strict';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let data=null,result=null,source='',selected=null,checkedAt=null,configDirty=false;
const statusLabels={pending:'待确认',data_error:'数据异常',process_change:'真实工况变化'};
function time(t,full=false){if(t===null)return '时间无效';const d=new Date(t);return full?d.toLocaleString('zh-CN',{hour12:false}):d.toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false});}
function notify(s=''){$('message').textContent=s;}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}
function confirmReplace(){return !result?.events.some(e=>e.status!=='pending'||e.note)||confirm('切换数据或重新检查会清空当前人工核查。请确认已导出需要保留的结果。继续吗？');}
function load(d,name){data=d;source=name;result=null;selected=null;notify();$('file-label').textContent=`${name} · ${d.rows.length} 条记录`;
 $('verdict').textContent='请确认字段后运行检查';$('verdict-detail').textContent='当前数据尚未完成检查。';$('verdict-badge').textContent='未检查';['count','flagged','pending','completeness'].forEach(id=>$(id).textContent='—');$('period').textContent='等待检查';$('review-progress').textContent='尚未检查';$('event-count').textContent='0';$('chart').innerHTML='';$('events').innerHTML='';$('evidence').hidden=true;$('selection').textContent='点击下方事件查看证据。';
 const specs=[['time','时间','timestamp|time|date|时间|日期'],['do','溶解氧 DO','^do$|^do_|溶解氧'],['air','供气量','air|气量'],['temp','温度','temp|温度']];
 $('mapping').innerHTML=specs.map(([k,label,re])=>{const match=d.headers.find(h=>new RegExp(re,'i').test(h));const options='<option value="">不映射</option>'+d.headers.map(h=>`<option value="${esc(h)}" ${h===match?'selected':''}>${esc(h)}</option>`).join('');let unit=k==='do'?'<option value="mg/L">mg/L</option><option value="ug/L">µg/L</option>':k==='air'?'<option value="m3/h">m³/h</option><option value="m3/min">m³/min</option>':k==='temp'?'<option value="C">°C</option><option value="F">°F</option>':'';return `<label class="field">${label}<div class="mapping-line" ${k==='time'?'style="grid-template-columns:1fr"':''}><select id="map-${k}" aria-label="${label}映射">${options}</select>${unit?`<select id="unit-${k}" aria-label="${label}单位">${unit}</select>`:''}</div></label>`;}).join('');run(false);}
function getConfig(){const n=id=>{if($(id).value.trim()==='')throw new Error('检查规则不能留空，请填写范围及阈值。');return Number($(id).value);};return{bounds:{do:[n('do-min'),n('do-max')],air:[n('air-min'),n('air-max')],temp:[n('temp-min'),n('temp-max')]},flatMinutes:n('flat-minutes'),jumpRate:n('jump-rate'),units:{do:$('unit-do').value,air:$('unit-air').value,temp:$('unit-temp').value}};}
function run(ask=true){if(!data)return notify('请先载入演示数据或上传 CSV。');if(ask&&!confirmReplace())return;try{const map=Object.fromEntries(['time','do','air','temp'].map(k=>[k,$('map-'+k).value]));result=ADC.analyze(data,map,getConfig());selected=null;checkedAt=new Date().toISOString();configDirty=false;$('dirty').hidden=true;notify();$('metric').innerHTML=result.keys.map(k=>`<option value="${k}">${ADC.LABELS[k]}</option>`).join('');$('filter').value='all';render();}catch(e){configDirty=true;$('dirty').hidden=false;notify(e.message);}}
function render(){if(!result)return;renderSummary();renderChart();renderEvents();renderEvidence();}
function renderSummary(){const a=ADC.assessment(result);$('verdict').textContent=a.title;$('verdict-detail').textContent=a.detail;$('verdict-badge').textContent=a.bad?'需处理':a.pending?'需核查':a.retainedHard?'需复检':'初筛完成';$('verdict-badge').className='status-badge'+(!a.bad&&!a.pending&&!a.retainedHard?' good':'');$('count').textContent=result.records.length;$('flagged').textContent=result.flagged.length;$('pending').textContent=a.pending;$('completeness').textContent=result.completeness.toFixed(1)+'%';$('review-progress').textContent=`已核查 ${result.events.length-a.pending} / ${result.events.length} 项`;$('event-count').textContent=result.events.length;const ts=result.ordered;$('period').textContent=ts.length?`${((ts[ts.length-1].t-ts[0].t)/3600000).toFixed(1)} 小时 · 中位间隔 ${result.interval?(result.interval/60000).toFixed(1)+' min':'未知'}`:'无有效时间';}
function renderChart(){const k=$('metric').value,rs=result.ordered;const valid=rs.filter(r=>r.v[k]!==null);if(!valid.length){$('chart').innerHTML='<div class="empty">当前指标没有可绘制的有效数据。</div>';return;}const W=1000,H=285,L=55,R=18,T=24,B=42,x0=rs[0].t,x1=rs[rs.length-1].t||x0+1;let lo=Math.min(...valid.map(r=>r.v[k])),hi=Math.max(...valid.map(r=>r.v[k]));const pad=Math.max((hi-lo)*.16,.2);lo-=pad;hi+=pad;const x=t=>L+(t-x0)/Math.max(x1-x0,1)*(W-L-R),y=v=>T+(hi-v)/(hi-lo)*(H-T-B);let svg=`<svg viewBox="0 0 ${W} ${H}" role="img" aria-label="${esc(ADC.LABELS[k])}原始数据与异常标记"><title>${esc(ADC.LABELS[k])}趋势图，时间按本机时区显示</title>`;
 const ev=result.events.find(e=>e.id===selected);if(ev&&ev.start!==null)svg+=`<rect x="${x(ev.start)-3}" y="${T}" width="${Math.max(7,x(ev.end)-x(ev.start)+6)}" height="${H-T-B}" fill="#fff0d9"/>`;
 for(let j=0;j<=4;j++){const v=lo+(hi-lo)*j/4,yy=y(v);svg+=`<line x1="${L}" y1="${yy}" x2="${W-R}" y2="${yy}" stroke="#e5edef"/><text x="${L-10}" y="${yy+4}" text-anchor="end" class="chart-label">${v.toFixed(1)}</text>`;}for(let j=0;j<=6;j++){const t=x0+(x1-x0)*j/6;svg+=`<text x="${x(t)}" y="${H-16}" text-anchor="middle" class="chart-label">${time(t)}</text>`;}
 let path='',last=null;for(const r of rs){if(r.v[k]===null){last=null;continue;}const gap=last&&result.interval&&r.t-last.t>result.interval*1.5;path+=`${!last||gap?'M':'L'}${x(r.t).toFixed(2)},${y(r.v[k]).toFixed(2)} `;last=r;}svg+=`<path d="${path}" fill="none" stroke="#087f83" stroke-width="2" stroke-linejoin="round"/>`;
 const flagged=new Set(result.events.filter(e=>e.key===k||e.key==='time').flatMap(e=>e.rows));let dots=0;for(const r of valid)if(flagged.has(r.i)&&dots++<1500)svg+=`<circle cx="${x(r.t)}" cy="${y(r.v[k])}" r="3.3" fill="#dc7a48" stroke="white" stroke-width="1"><title>CSV 记录 ${r.i+2} · ${time(r.t,true)} · ${r.v[k]}</title></circle>`;
 svg+=`<text x="${L}" y="13" class="chart-label">${k==='do'?'mg/L':k==='air'?'m³/h':'°C'}</text></svg>`;$('chart').innerHTML=svg;$('chart-caption').textContent=`${ADC.LABELS[k]} · 本机时区 ${Intl.DateTimeFormat().resolvedOptions().timeZone} · 保留原始变化`;}
function renderEvents(){const filter=$('filter').value,es=result.events.filter(e=>filter==='all'||e.status===filter);$('events').innerHTML=es.length?es.map(e=>`<tr class="event-row ${e.id===selected?'selected':''}" data-id="${e.id}" tabindex="0" aria-label="查看${esc(e.type)}证据"><td><span class="tag ${e.hard?'hard':''}">${esc(e.type)}</span><br><b>${ADC.LABELS[e.key]}</b><div class="small">${e.id} · ${e.rows.length} 条记录</div></td><td>${time(e.start)} – ${time(e.end)}<div class="small">${e.start===null?'':new Date(e.start).toLocaleDateString('zh-CN')}</div></td><td>${esc(e.detail)}<div class="small">${esc(e.advice)}</div></td><td><select data-review="${e.id}" aria-label="${e.id}核查结论">${Object.entries(statusLabels).map(([v,l])=>`<option value="${v}" ${e.status===v?'selected':''}>${l}</option>`).join('')}</select><textarea data-note="${e.id}" placeholder="记录判断依据（建议填写）" aria-label="${e.id}核查依据">${esc(e.note)}</textarea></td></tr>`).join(''):'<tr><td colspan="4" class="empty">'+(result.events.length?'当前筛选条件下没有事件。':'未触发当前检查规则。仍需确认仪表校准与建模边界。')+'</td></tr>';}
function selectEvent(id){selected=id;const e=result.events.find(e=>e.id===id);if(e.key!=='time')$('metric').value=e.key;renderChart();document.querySelectorAll('.event-row').forEach(r=>r.classList.toggle('selected',r.dataset.id===id));renderEvidence();$('selection').textContent=`已定位 ${id}：${e.type}。${e.detail}  下方原始证据保留源文件值；单位转换仅用于检查。`;}
function renderEvidence(){const e=result.events.find(e=>e.id===selected);$('evidence').hidden=!e;if(!e)return;const rows=e.rows.slice(0,30).map(i=>data.rows[i]);$('evidence').innerHTML=`<h3>${e.id} 原始证据 · 最多展示 30 条</h3><table><thead><tr><th>CSV 记录号</th>${data.headers.map(h=>`<th>${esc(h)}</th>`).join('')}</tr></thead><tbody>${rows.map((r,j)=>`<tr><td>${e.rows[j]+2}</td>${r.map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</tbody></table>`;}
function report(){return{project:'Aeration Data Check',version:'0.1.0',source,caseContext:'Inspired by Eindhoven WRRF. Built-in data are synthetic, NOT Eindhoven measurements.',generatedAt:new Date().toISOString(),checkedAt,timezone:Intl.DateTimeFormat().resolvedOptions().timeZone,recordCount:result.records.length,flaggedRecordCount:result.flagged.length,completeness:result.completeness,mapping:result.mapping,config:result.config,assessment:ADC.assessment(result),events:result.events.map(e=>({...e,csvRecordNumbers:e.rows.map(i=>i+2),startISO:e.start===null?null:new Date(e.start).toISOString(),endISO:e.end===null?null:new Date(e.end).toISOString()})),notes:['Original measurements were not changed.','Quality flags are not proof of sensor failure.','Human review does not remove rule flags or repair data.','Astra is not used in v0.1.'],reference:'Daneshgar et al. (2024), Water Environment Research, 96(3), e11016. https://doi.org/10.1002/wer.11016'};}
function allowExport(){if(!result){notify('请先运行检查。');return false;}if(configDirty){notify('字段或规则已修改。请重新检查后再导出，避免使用旧结果。');return false;}return true;}
$('demo').onclick=()=>{if(confirmReplace())load(ADC.demo(true),'教学模拟 · 问题数据');};$('clean-demo').onclick=()=>{if(confirmReplace())load(ADC.demo(false),'教学模拟 · 正常对照');};$('sample').onclick=()=>{const d=ADC.demo(true);download('synthetic-aeration-demo.csv',ADC.toCSV(d.headers,d.rows),'text/csv;charset=utf-8');};
$('file').onchange=async e=>{const f=e.target.files[0];if(!f)return;if(!confirmReplace()){e.target.value='';return;}try{if(f.size>8*1024*1024)throw new Error('文件超过 8 MB，请先截取所需数据。');const text=await f.text();if(text.includes('\ufffd'))throw new Error('文件可能不是 UTF-8 编码，请另存为 UTF-8 CSV 后上传。');const d=ADC.parseCSV(text);load(d,f.name);}catch(err){notify(err.message);}e.target.value='';};
$('run').onclick=()=>run();$('metric').onchange=()=>result&&renderChart();$('filter').onchange=()=>result&&renderEvents();
document.querySelector('aside').addEventListener('change',e=>{if(e.target.id==='file')return;if(result){configDirty=true;$('dirty').hidden=false;}});
$('events').addEventListener('click',e=>{if(e.target.closest('select,textarea'))return;const row=e.target.closest('[data-id]');if(row)selectEvent(row.dataset.id);});$('events').addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&e.target.matches('tr[data-id]')){e.preventDefault();selectEvent(e.target.dataset.id);}});
$('events').addEventListener('change',e=>{if(e.target.dataset.review){const ev=result.events.find(x=>x.id===e.target.dataset.review);ev.status=e.target.value;renderSummary();}});$('events').addEventListener('input',e=>{if(e.target.dataset.note)result.events.find(x=>x.id===e.target.dataset.note).note=e.target.value;});
$('export-csv').onclick=()=>{if(!allowExport())return;const rows=data.rows.map((r,i)=>{const es=result.events.filter(e=>e.rows.includes(i));return [...r,es.map(e=>e.id).join('|'),es.map(e=>e.type).join('|'),es.map(e=>`${e.id}:${statusLabels[e.status]}`).join('|'),es.map(e=>`${e.id}:${e.note}`).join('|')];});download('aeration-quality-marked.csv',ADC.toCSV([...data.headers,'adc_event_ids','adc_flags','adc_review','adc_notes'],rows),'text/csv;charset=utf-8');};
$('export-json').onclick=()=>{if(allowExport())download('aeration-quality-report.json',JSON.stringify(report(),null,2),'application/json');};
$('export-report').onclick=()=>{if(!allowExport())return;const r=report();const html=`<!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>曝气数据质量检查报告</title><style>body{font:15px/1.8 system-ui,"Microsoft YaHei",sans-serif;max-width:1000px;margin:45px auto;padding:0 25px;color:#173b47}h1{font-size:27px}h2{margin-top:30px;font-size:20px}table{border-collapse:collapse;width:100%;font-size:12px}th,td{border:1px solid #d4e0e3;padding:10px;text-align:left;vertical-align:top}th{background:#edf7f7}pre{white-space:pre-wrap;background:#f4f7f8;padding:16px;font-size:12px}small{color:#667c83}@media print{body{margin:0}tr{break-inside:avoid}}</style><h1>曝气分区数据质量检查报告</h1><p><b>数据来源：</b>${esc(r.source)}<br><b>检查时间：</b>${esc(r.checkedAt)}<br><b>时区：</b>${esc(r.timezone)}</p><p><b>案例说明：</b>参考埃因霍温 WRRF 数字孪生的数据预处理思路。内置数据为教学模拟，非该厂实测。本报告不代表该厂实际运行状况。</p><h2>${esc(r.assessment.title)}</h2><p>${esc(r.assessment.detail)}</p><p>原始记录 ${r.recordCount} 条；有标记记录 ${r.flaggedRecordCount} 条；字段完整率 ${r.completeness.toFixed(1)}%；待确认 ${r.assessment.pending} 项。</p><h2>事件与人工核查</h2><table><tr><th>事件</th><th>时间 / 记录</th><th>证据</th><th>人工结论</th></tr>${r.events.map(e=>`<tr><td>${e.id}<br>${esc(e.type)} · ${ADC.LABELS[e.key]}</td><td>${esc(e.startISO||'时间无效')}<br>${esc(e.endISO||'')}<br>CSV 记录：${e.csvRecordNumbers.join(', ')}</td><td>${esc(e.detail)}<br>${esc(e.advice)}</td><td>${statusLabels[e.status]}<br>${esc(e.note||'未填写依据')}</td></tr>`).join('')}</table>${!r.events.length?'<p>未触发规则。</p>':''}<h2>字段映射及规则快照</h2><pre>${esc(JSON.stringify({mapping:r.mapping,config:r.config},null,2))}</pre><h2>结果边界</h2><p>测量值未被修改或删除。原始标记与人工判断分别保存；真实工况解释不会修复缺测或时间结构问题。本报告未检查仪表校准、物料平衡及模型精度，不能单独证明数据适合任意模型。v0.1 未调用 Astra。导出的 CSV 对可能被电子表格执行的文本添加前导单引号，数值不变。</p><p><small>${esc(r.reference)}</small></p></html>`;download('aeration-quality-report.html',html,'text/html;charset=utf-8');};
$('help').onclick=()=>$('guide').showModal();$('close-help').onclick=$('start').onclick=()=>$('guide').close();
load(ADC.demo(true),'教学模拟 · 问题数据');
